version: "3.3"
services:
  db_mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=final_project
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./mysql-data:/var/lib/mysql