package com.gmail.yauheniylebedzeu.service.constant;

public interface ValidationConstant {
    String MIN_ITEM_PRICE = "0.00";
    int MIN_LENGTH_OF_ITEM_NAME = 2;
    int MAX_LENGTH_OF_ITEM_NAME = 50;
    int MIN_LENGTH_OF_ITEM_DESCRIPTION = 5;
    int MAX_LENGTH_OF_ITEM_DESCRIPTION = 200;
    int COUNT_OF_INTEGERS_IN_PRICE = 4;
    int COUNT_OF_FRACTIONS_IN_PRICE = 2;

    int MIN_LENGTH_OF_ARTICLE_TITLE = 3;
    int MAX_LENGTH_OF_ARTICLE_TITLE = 50;
    int MIN_LENGTH_OF_ARTICLE_SYNOPSIS = 20;
    int MAX_LENGTH_OF_ARTICLE_SYNOPSIS = 200;
    int MIN_LENGTH_OF_ARTICLE_CONTENT = 100;
    int MAX_LENGTH_OF_ARTICLE_CONTENT = 1000;
}